".vimrc
"
" Some references
" http://vimdoc.sourceforge.net/htmldoc/options.html
"
" Needs:
" - wombat256 color scheme
" http://www.vim.org/scripts/script.php?script_id=2465
" - pathogen plugin
" https://github.com/tpope/vim-pathogen

" pathogen commands
filetype off
"call pathogen#runtime_append_all_bundles()
call pathogen#incubate()
call pathogen#helptags()

" For multi-byte character support (CJK support, for example):
"set fileencodings=ucs-bom,utf-8,cp936,big5,euc-jp,euc-kr,gb18030,latin1
       
" Use Vim settings, rather than Vi settings
" This must be first, because it changes other options as a side effect
set nocompatible

" Make backspace behave in a sane manner
set backspace=indent,eol,start

" Switch syntax highlighting on
syntax on

" Enable file type detection and do language-dependent indenting
filetype plugin indent on

" PEAR Coding standards
" http://pear.php.net/manual/en/standards.php
" " Number of spaces that a <Tab> in the file counts for
set tabstop=4
set softtabstop=4

" Number of spaces to use for each step of (auto)indent
set shiftwidth=4
 
" Use the appropriate number of spaces to insert a <Tab>.
" Spaces are used in indents with the '>' and '<' commands
" and when 'autoindent' is on. To insert a real tab when
" 'expandtab' is on, use CTRL-V <Tab>.
set expandtab
 
" When on, a <Tab> in front of a line inserts blanks
" according to 'shiftwidth'. 'tabstop' is used in other
" places. A <BS> will delete a 'shiftwidth' worth of space
" at the start of the line.
set smarttab
 
" Show (partial) command in status line.
set showcmd

" Show line numbers.
set number

" When a bracket is inserted, briefly jump to the matching
" one. The jump is only done if the match can be seen on the
" screen. The time to show the match can be set with
" 'matchtime'.
set showmatch
 
" When there is a previous search pattern, highlight all
" its matches.
"set hlsearch
 
" While typing a search command, show immediately where the
" so far typed pattern matches.
set incsearch
 
" Ignore case in search patterns.
set ignorecase
 
" Override the 'ignorecase' option if the search pattern
" contains upper case characters.
set smartcase
 
" Influences the working of <BS>, <Del>, CTRL-W
" and CTRL-U in Insert mode. This is a list of items,
" separated by commas. Each item allows a way to backspace
" over something.
set backspace=2
 
" Copy indent from current line when starting a new line
" (typing <CR> in Insert mode or when using the "o" or "O"
" command)
set autoindent
 
" Maximum width of text that is being inserted. A longer
" line will be broken after white space to get this width
"set textwidth=79
 
" This is a sequence of letters which describes how
" automatic formatting is to be done.
"
" letter    meaning when present in 'formatoptions'
" ------    ---------------------------------------
" c         Auto-wrap comments using textwidth, inserting
"           the current comment leader automatically.
" q         Allow formatting of comments with "gq".
" r         Automatically insert the current comment leader
"           after hitting <Enter> in Insert mode.
" t         Auto-wrap text using textwidth (does not apply
"           to comments)
set formatoptions=c,q,r,t
 
" Show the line and column number of the cursor position,
" separated by a comma.
set ruler
 
" Try to use colors that look good on a dark background
"set background=dark

" Enable the use of the mouse.
"set mouse=a
 
"set paste

" python settings
set foldmethod=indent
set foldlevel=99

" map pep8
let g:pep8_map='<leader>8'

" python SuperTab plugin
au FileType python set omnifunc=pythoncomplete#Complete
let g:SuperTabDefaultCompletionType = "context"
set completeopt=menuone,longest,preview

" configure SuperTab with c-space instead tab
let g:SuperTabMappingForward = '<nul>'
let g:SuperTabMappingBackward = '<s-nul>'

" Enable 256 colors
set t_Co=256

" Color scheme
"colorscheme wombat256
colorscheme molokai
let g:molokai_original = 1

